baseURL = "https://carjed.github.io/audiences/"
languageCode = "en"
title = "audiences"
theme = "mondrian"
pygmentsCodeFences = true   # Enable triple backtick 'code fence' markdown
pygmentsUseClasses = false  # Add inline styles, no need to compile extra CSS
Paginate = 6
publishDir = "docs"
# ignoreFiles = [ "reports/_.*" ]
# ignorefiles = [ "reports/*" ]


[taxonomies]
  tag = "tags"

[params]
  showHeader = true
  showTags = true
  debug = false
  [params.colors]
#    test = "orangered"
    reports = "gold"
    summary = "limegreen"
    page = "white"

[menu]
  [[menu.main]]
    name= "reports"
    url = "reports"
    weight = 2
  [[menu.main]]
    name = "search"
    url = "search"
    weight = 3
 # [[menu.main]]
 #   name = "test"
 #   url = "/test"
 #   weight = 3


[outputs]
  home = ["HTML", "JSON", "RSS"]
#  page = ["HTML", "JSON", "RSS"]

