site_name: audiences
site_url: https://github.com/carjed/audiences
repo_url: https://github.com/carjed/audiences
docs_dir: _docs
nav:
  - Home: index.md
  - Usage: usage.md
  - FAQ: faq.md
  - Support: support.md
theme: cinder
